import { Inter } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'

const sukhumvit = localFont({ src: '../../public/fonts/SukhumvitSet-Text.ttf', variable: '--font-sukhumvit' });
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Setthapong Port",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${sukhumvit.variable} font-sans`}>      
        {children}
      </body>
    </html>
  );
}
